apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job-1-0-gamma
    app.kubernetes.io/part-of: access-1-0-gamma
  name: segment-backup-job-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: segment-backup-job-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: segment-backup-job-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/segment-backup-job-1-0-gamma@sha256:73f12e684395048bb1cd7f3f0ae4fdf97703e0012257e57152b4f7f8426644f5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
