apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job-1-0-gamma
    app.kubernetes.io/part-of: access-1-0-gamma
  name: segment-backup-job-1-0-gamma
spec:
  ports:
  - port: 1
    targetPort: 1
  selector:
    app.kubernetes.io/instance: segment-backup-job-1-0-gamma
status:
  loadBalancer: {}
