apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-backup-job-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/segment-backup-job-1-0-gamma@sha256:2038d3223102f5f50d3af3d7a6affc3f2c3493e1e627f7df75534e8ddc15e27a
        name: container-image
        resources: {}
status: {}
