apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job-1-0-gamma
    app.kubernetes.io/part-of: access-1-0-gamma
  name: segment-backup-job-1-0-gaacwf
spec:
  port:
    targetPort: 1
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: segment-backup-job-1-0-gamma
    weight: 100
status: {}
