apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/client-server-1-0-gamma@sha256:a49c9eec4b8d73f7b106e14a6c51c8e68c702b4123bc58d033cefbd41c146966
        name: container-image
        resources: {}
status: {}
