apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/client-server-1-0-gamma@sha256:672685f069f65bbf37dc2aa517c3ce157b2818d7546d90b6d686e826b9682b69
        name: container-image
        resources: {}
status: {}
