apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/client-server-1-0-gamma@sha256:731421b2e0c32daead29c763c2288ee0c188b20868102b2f51201ddb962c057a
        name: container-image
        resources: {}
status: {}
