apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-server-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-server-1-0-gamma
    app.kubernetes.io/part-of: access-1-0-gamma
  name: client-server-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: client-server-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: client-server-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/access-1-0-gamma/client-server-1-0-gamma@sha256:7525c2751b79cff7ab5706106f1cbbcc144ad99d8d3eba03e614b82ff9ca2f1e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
